jobs:

- job: "LinuxDistro"
  displayName: "Linux Distro Build"
  pool:
    vmImage: 'ubuntu-latest'

  strategy:
    matrix:
      ubuntu14:
        containerImage: ubuntu:14.04
        dockerfile: Dockerfile.ubuntu
      ubuntu16:
        containerImage: ubuntu:16.04
        dockerfile: Dockerfile.ubuntu
      ubuntu18:
        containerImage: ubuntu:18.04
        dockerfile: Dockerfile.ubuntu
      ubuntu-rolling:
        containerImage: ubuntu:rolling
        dockerfile: Dockerfile.ubuntu
      ubuntu-devel:
        containerImage: ubuntu:devel
        dockerfile: Dockerfile.ubuntu
      fedora-latest:
        containerImage: fedora:latest
        dockerfile: Dockerfile.fedora

  steps:
  - script: docker build -f $(dockerfile) --build-arg IMAGE=$(containerImage) -t base .
    displayName: 'Install build dependencies'

  - script: docker run -v $(pwd):/open-vm-tools -w /open-vm-tools base ./build.sh
    displayName: 'Build'

- job: "GUIX"
  displayName: "GUIX Docker Build"
  continueOnError: True
  pool:
    vmImage: "ubuntu-latest"

  steps:
  - script: docker build -f Dockerfile.guix -t alpine-guix .
    displayName: 'GUIX Install'

  - script: |
      docker run -d -v $(pwd):/open-vm-tools --privileged --name alpine-guix alpine-guix
      docker exec -w /open-vm-tools --privileged alpine-guix guix environment --pure --container --manifest=open-vm-tools-manifest.scm -- ./build.sh
      RET=$?
      docker stop alpine-guix
      exit $RET
    displayName: 'Build'

- job: "GUIXNative"
  displayName: "GUIX Native Build"
  pool:
    vmImage: "ubuntu-latest"

  steps:
  - script: |
      sudo apt-get remove --purge unscd
      sudo apt-get install -y expect
      wget https://git.savannah.gnu.org/cgit/guix.git/plain/etc/guix-install.sh
      chmod +x ./guix-install.sh
      wget https://sv.gnu.org/people/viewgpg.php?user_id=15145 -qO - | gpg --import -
      sudo ./install-guix.sh
    displayName: 'GUIX Native Install'

  - script: guix environment --pure --container --manifest=open-vm-tools-manifest.scm -- ./build.sh
    displayName: 'Build'
