jobs:

- job: "GUIX"
  displayName: "GUIX Docker Build"
  continueOnError: True
  pool:
    vmImage: "ubuntu-latest"

  steps:
  - script: docker build -f Dockerfile.guix -t alpine-guix .
    displayName: 'GUIX Install'

  - script: |
      docker run -d -v $(pwd):/open-vm-tools --privileged --name alpine-guix alpine-guix
      docker exec -w /open-vm-tools --privileged alpine-guix guix build --file=open-vm-tools.scm
      RET=$?
      docker stop alpine-guix
      exit $RET
    displayName: 'Build'

- job: "GUIXNative"
  displayName: "GUIX Native Build"
  pool:
    vmImage: "ubuntu-latest"

  steps:
  - script: |
      sudo apt-get remove --purge unscd
      sudo apt-get install -y expect
      wget https://git.savannah.gnu.org/cgit/guix.git/plain/etc/guix-install.sh
      chmod +x ./guix-install.sh
      wget https://sv.gnu.org/people/viewgpg.php?user_id=15145 -qO - | gpg --import -
      sudo ./install-guix.sh
    displayName: 'GUIX Native Install'

  - script: guix build --file=open-vm-tools.scm
    displayName: 'Build'
